name: Bug Report
description: Report a bug with the Voice Satellite Card
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Before submitting, please go through the checklist below to make sure the issue isn't a configuration problem.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites checklist
      description: Please confirm you've checked all of these before opening an issue.
      options:
        - label: I have installed the required [Voice Satellite Card Integration](https://github.com/jxlarrea/voice-satellite-card-integration).
          required: true
        - label: I am running **Home Assistant 2025.2.1** or later.
          required: true
        - label: I am accessing Home Assistant over **HTTPS** (or localhost). Microphone access requires a secure context.
          required: true
        - label: I have granted **microphone permission** when prompted by the browser (a user gesture like tapping the mic button is required to trigger the permission prompt; in Fully Kiosk, enable **Web Content Settings → Enable Microphone Access** and **Autoplay Audio**)
          required: true
        - label: I have a **wake word service** (e.g., openWakeWord, microWakeWord) available to Home Assistant as an add-on or Wyoming integration.
          required: true
        - label: I have **wake word detection enabled in my Assist pipeline**. I've confirmed this by going to Settings → Voice assistants → my pipeline → ⋮ three-dot menu, and verifying a wake word is selected.
          required: true
        - label: My Assist pipeline has **Speech-to-Text** (e.g., Whisper) and **Text-to-Speech** (e.g., Piper) configured.
          required: true
        - label: I have tested the pipeline works independently (e.g., via the Assist dialog in the HA sidebar).
          required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what's happening.
      placeholder: "When I tap the microphone button, nothing happens..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide the following details.
      value: |
        - Home Assistant version:
        - Voice Satellite Card version:
        - Voice Satellite Card Integration version (if installed):
        - Browser / app:
        - Device (tablet model, phone, desktop):
        - Wake word service (e.g., openWakeWord, microWakeWord):
        - STT engine:
        - TTS engine:
    validations:
      required: true

  - type: textarea
    id: console
    attributes:
      label: Browser console output
      description: |
        Open browser dev tools (F12), go to the Console tab, and paste any errors here. You can also enable `debug: true` in the card config for more verbose output.
      render: shell

  - type: textarea
    id: ha-logs
    attributes:
      label: Home Assistant logs
      description: |
        Any relevant logs from Settings → System → Logs. Filter by "voice_satellite" or "assist_pipeline" if possible.
      render: shell