name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear description of what you'd like to see added or changed.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Why would this feature be useful? What problem does it solve?
    validations:
      required: true