---
name: General Issue
about: For anything that doesn't fit the Bug Report or Feature Request templates
title: ''
labels: ''
assignees: ''
---

<!--
Thanks for opening an issue! Please fill out the sections below so we can help you faster.
If this is a bug, consider using the Bug Report template instead — it has a checklist that helps rule out common setup issues.
-->

## Before you start

Please confirm:
- [ ] I have read the [Troubleshooting section](https://github.com/jxlarrea/Voice-Satellite-Card-for-Home-Assistant#troubleshooting) in the README
- [ ] I have confirmed my Assist pipeline works independently (e.g., via the Assist dialog in the HA sidebar)
- [ ] I have a wake word service (e.g., openWakeWord, microWakeWord) available to Home Assistant and enabled in my pipeline

## Description

<!-- Describe your issue or question clearly -->


## Environment

- **Home Assistant version:**
- **Voice Satellite Card version:**
- **Voice Satellite Card Integration version (if installed):**
- **Browser / app:**
- **Device:**

## Additional context

<!-- Console logs, screenshots, YAML config, etc. -->